#!/usr/bin/env ruby

require './angelco'
require 'yaml'

# parse arguments
if ARGV[0] == nil
    puts "Usage: ./vulcano <config-file.yml>"
    exit
end

# read yml configuration
config = YAML.load_file(ARGV[0])
driver = config['driver']
username = config['username']
password = config['password']
keywords = config['keywords'].split('|')
maxpages = config['maxpages']
cover = config['cover']

# fuck it
fucker = AngelcoDriver.new()
fucker.open
fucker.login(username, password)
fucker.enumerate(keywords, maxpages)
#fucker.apply(cover)

